### ISSUE TITLE
Small optimization

### ISSUE THREAD

**Issue by mfalkvidd** [darksidelemm/satnogs-unwinder#2]
https://github.com/darksidelemm/satnogs-unwinder/blob/f36ebead4daaf0b2de6e93f38a2f9644a329cad5/unwind.py#L198

you could do_obs.extend(_obs_temp) instead of looping through  all elements

**Comment by darksidelemm** [comment]
aha, it was .extend that I was looking for.... (I was using append, which didn't work). Cheers.

**Comment by darksidelemm** [comment]
OK, this has been changed, thanks!
